/* automatically generated by rust-bindgen */

use crate::*;

pub type __uint8_t = libc::c_uchar;
pub type __uint32_t = libc::c_uint;
pub type __int64_t = libc::c_long;
pub type __off_t = libc::c_long;
pub type __off64_t = libc::c_long;
pub type Uint8 = u8;
pub type Uint32 = u32;
pub type Sint64 = i64;
extern "C" {
    pub fn IMG_Linked_Version() -> *const SDL_version;
}
pub const IMG_InitFlags_IMG_INIT_JPG: IMG_InitFlags = 1;
pub const IMG_InitFlags_IMG_INIT_PNG: IMG_InitFlags = 2;
pub const IMG_InitFlags_IMG_INIT_TIF: IMG_InitFlags = 4;
pub const IMG_InitFlags_IMG_INIT_WEBP: IMG_InitFlags = 8;
pub type IMG_InitFlags = u32;
extern "C" {
    pub fn IMG_Init(flags: libc::c_int) -> libc::c_int;
}
extern "C" {
    pub fn IMG_Quit();
}
extern "C" {
    pub fn IMG_LoadTyped_RW(
        src: *mut SDL_RWops,
        freesrc: libc::c_int,
        type_: *const libc::c_char,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn IMG_Load(file: *const libc::c_char) -> *mut SDL_Surface;
}
extern "C" {
    pub fn IMG_Load_RW(src: *mut SDL_RWops, freesrc: libc::c_int) -> *mut SDL_Surface;
}
extern "C" {
    pub fn IMG_LoadTexture(
        renderer: *mut SDL_Renderer,
        file: *const libc::c_char,
    ) -> *mut SDL_Texture;
}
extern "C" {
    pub fn IMG_LoadTexture_RW(
        renderer: *mut SDL_Renderer,
        src: *mut SDL_RWops,
        freesrc: libc::c_int,
    ) -> *mut SDL_Texture;
}
extern "C" {
    pub fn IMG_LoadTextureTyped_RW(
        renderer: *mut SDL_Renderer,
        src: *mut SDL_RWops,
        freesrc: libc::c_int,
        type_: *const libc::c_char,
    ) -> *mut SDL_Texture;
}
extern "C" {
    pub fn IMG_isICO(src: *mut SDL_RWops) -> libc::c_int;
}
extern "C" {
    pub fn IMG_isCUR(src: *mut SDL_RWops) -> libc::c_int;
}
extern "C" {
    pub fn IMG_isBMP(src: *mut SDL_RWops) -> libc::c_int;
}
extern "C" {
    pub fn IMG_isGIF(src: *mut SDL_RWops) -> libc::c_int;
}
extern "C" {
    pub fn IMG_isJPG(src: *mut SDL_RWops) -> libc::c_int;
}
extern "C" {
    pub fn IMG_isLBM(src: *mut SDL_RWops) -> libc::c_int;
}
extern "C" {
    pub fn IMG_isPCX(src: *mut SDL_RWops) -> libc::c_int;
}
extern "C" {
    pub fn IMG_isPNG(src: *mut SDL_RWops) -> libc::c_int;
}
extern "C" {
    pub fn IMG_isPNM(src: *mut SDL_RWops) -> libc::c_int;
}
extern "C" {
    pub fn IMG_isSVG(src: *mut SDL_RWops) -> libc::c_int;
}
extern "C" {
    pub fn IMG_isTIF(src: *mut SDL_RWops) -> libc::c_int;
}
extern "C" {
    pub fn IMG_isXCF(src: *mut SDL_RWops) -> libc::c_int;
}
extern "C" {
    pub fn IMG_isXPM(src: *mut SDL_RWops) -> libc::c_int;
}
extern "C" {
    pub fn IMG_isXV(src: *mut SDL_RWops) -> libc::c_int;
}
extern "C" {
    pub fn IMG_isWEBP(src: *mut SDL_RWops) -> libc::c_int;
}
extern "C" {
    pub fn IMG_LoadICO_RW(src: *mut SDL_RWops) -> *mut SDL_Surface;
}
extern "C" {
    pub fn IMG_LoadCUR_RW(src: *mut SDL_RWops) -> *mut SDL_Surface;
}
extern "C" {
    pub fn IMG_LoadBMP_RW(src: *mut SDL_RWops) -> *mut SDL_Surface;
}
extern "C" {
    pub fn IMG_LoadGIF_RW(src: *mut SDL_RWops) -> *mut SDL_Surface;
}
extern "C" {
    pub fn IMG_LoadJPG_RW(src: *mut SDL_RWops) -> *mut SDL_Surface;
}
extern "C" {
    pub fn IMG_LoadLBM_RW(src: *mut SDL_RWops) -> *mut SDL_Surface;
}
extern "C" {
    pub fn IMG_LoadPCX_RW(src: *mut SDL_RWops) -> *mut SDL_Surface;
}
extern "C" {
    pub fn IMG_LoadPNG_RW(src: *mut SDL_RWops) -> *mut SDL_Surface;
}
extern "C" {
    pub fn IMG_LoadPNM_RW(src: *mut SDL_RWops) -> *mut SDL_Surface;
}
extern "C" {
    pub fn IMG_LoadSVG_RW(src: *mut SDL_RWops) -> *mut SDL_Surface;
}
extern "C" {
    pub fn IMG_LoadTGA_RW(src: *mut SDL_RWops) -> *mut SDL_Surface;
}
extern "C" {
    pub fn IMG_LoadTIF_RW(src: *mut SDL_RWops) -> *mut SDL_Surface;
}
extern "C" {
    pub fn IMG_LoadXCF_RW(src: *mut SDL_RWops) -> *mut SDL_Surface;
}
extern "C" {
    pub fn IMG_LoadXPM_RW(src: *mut SDL_RWops) -> *mut SDL_Surface;
}
extern "C" {
    pub fn IMG_LoadXV_RW(src: *mut SDL_RWops) -> *mut SDL_Surface;
}
extern "C" {
    pub fn IMG_LoadWEBP_RW(src: *mut SDL_RWops) -> *mut SDL_Surface;
}
extern "C" {
    pub fn IMG_ReadXPMFromArray(xpm: *mut *mut libc::c_char) -> *mut SDL_Surface;
}
extern "C" {
    pub fn IMG_SavePNG(surface: *mut SDL_Surface, file: *const libc::c_char) -> libc::c_int;
}
extern "C" {
    pub fn IMG_SavePNG_RW(
        surface: *mut SDL_Surface,
        dst: *mut SDL_RWops,
        freedst: libc::c_int,
    ) -> libc::c_int;
}
extern "C" {
    pub fn IMG_SaveJPG(
        surface: *mut SDL_Surface,
        file: *const libc::c_char,
        quality: libc::c_int,
    ) -> libc::c_int;
}
extern "C" {
    pub fn IMG_SaveJPG_RW(
        surface: *mut SDL_Surface,
        dst: *mut SDL_RWops,
        freedst: libc::c_int,
        quality: libc::c_int,
    ) -> libc::c_int;
}
