/* automatically generated by rust-bindgen */

extern "C" {
    pub fn SDL_imageFilterMMXdetect() -> libc::c_int;
}
extern "C" {
    pub fn SDL_imageFilterMMXoff();
}
extern "C" {
    pub fn SDL_imageFilterMMXon();
}
extern "C" {
    pub fn SDL_imageFilterAdd(
        Src1: *mut libc::c_uchar,
        Src2: *mut libc::c_uchar,
        Dest: *mut libc::c_uchar,
        length: libc::c_uint,
    ) -> libc::c_int;
}
extern "C" {
    pub fn SDL_imageFilterMean(
        Src1: *mut libc::c_uchar,
        Src2: *mut libc::c_uchar,
        Dest: *mut libc::c_uchar,
        length: libc::c_uint,
    ) -> libc::c_int;
}
extern "C" {
    pub fn SDL_imageFilterSub(
        Src1: *mut libc::c_uchar,
        Src2: *mut libc::c_uchar,
        Dest: *mut libc::c_uchar,
        length: libc::c_uint,
    ) -> libc::c_int;
}
extern "C" {
    pub fn SDL_imageFilterAbsDiff(
        Src1: *mut libc::c_uchar,
        Src2: *mut libc::c_uchar,
        Dest: *mut libc::c_uchar,
        length: libc::c_uint,
    ) -> libc::c_int;
}
extern "C" {
    pub fn SDL_imageFilterMult(
        Src1: *mut libc::c_uchar,
        Src2: *mut libc::c_uchar,
        Dest: *mut libc::c_uchar,
        length: libc::c_uint,
    ) -> libc::c_int;
}
extern "C" {
    pub fn SDL_imageFilterMultNor(
        Src1: *mut libc::c_uchar,
        Src2: *mut libc::c_uchar,
        Dest: *mut libc::c_uchar,
        length: libc::c_uint,
    ) -> libc::c_int;
}
extern "C" {
    pub fn SDL_imageFilterMultDivby2(
        Src1: *mut libc::c_uchar,
        Src2: *mut libc::c_uchar,
        Dest: *mut libc::c_uchar,
        length: libc::c_uint,
    ) -> libc::c_int;
}
extern "C" {
    pub fn SDL_imageFilterMultDivby4(
        Src1: *mut libc::c_uchar,
        Src2: *mut libc::c_uchar,
        Dest: *mut libc::c_uchar,
        length: libc::c_uint,
    ) -> libc::c_int;
}
extern "C" {
    pub fn SDL_imageFilterBitAnd(
        Src1: *mut libc::c_uchar,
        Src2: *mut libc::c_uchar,
        Dest: *mut libc::c_uchar,
        length: libc::c_uint,
    ) -> libc::c_int;
}
extern "C" {
    pub fn SDL_imageFilterBitOr(
        Src1: *mut libc::c_uchar,
        Src2: *mut libc::c_uchar,
        Dest: *mut libc::c_uchar,
        length: libc::c_uint,
    ) -> libc::c_int;
}
extern "C" {
    pub fn SDL_imageFilterDiv(
        Src1: *mut libc::c_uchar,
        Src2: *mut libc::c_uchar,
        Dest: *mut libc::c_uchar,
        length: libc::c_uint,
    ) -> libc::c_int;
}
extern "C" {
    pub fn SDL_imageFilterBitNegation(
        Src1: *mut libc::c_uchar,
        Dest: *mut libc::c_uchar,
        length: libc::c_uint,
    ) -> libc::c_int;
}
extern "C" {
    pub fn SDL_imageFilterAddByte(
        Src1: *mut libc::c_uchar,
        Dest: *mut libc::c_uchar,
        length: libc::c_uint,
        C: libc::c_uchar,
    ) -> libc::c_int;
}
extern "C" {
    pub fn SDL_imageFilterAddUint(
        Src1: *mut libc::c_uchar,
        Dest: *mut libc::c_uchar,
        length: libc::c_uint,
        C: libc::c_uint,
    ) -> libc::c_int;
}
extern "C" {
    pub fn SDL_imageFilterAddByteToHalf(
        Src1: *mut libc::c_uchar,
        Dest: *mut libc::c_uchar,
        length: libc::c_uint,
        C: libc::c_uchar,
    ) -> libc::c_int;
}
extern "C" {
    pub fn SDL_imageFilterSubByte(
        Src1: *mut libc::c_uchar,
        Dest: *mut libc::c_uchar,
        length: libc::c_uint,
        C: libc::c_uchar,
    ) -> libc::c_int;
}
extern "C" {
    pub fn SDL_imageFilterSubUint(
        Src1: *mut libc::c_uchar,
        Dest: *mut libc::c_uchar,
        length: libc::c_uint,
        C: libc::c_uint,
    ) -> libc::c_int;
}
extern "C" {
    pub fn SDL_imageFilterShiftRight(
        Src1: *mut libc::c_uchar,
        Dest: *mut libc::c_uchar,
        length: libc::c_uint,
        N: libc::c_uchar,
    ) -> libc::c_int;
}
extern "C" {
    pub fn SDL_imageFilterShiftRightUint(
        Src1: *mut libc::c_uchar,
        Dest: *mut libc::c_uchar,
        length: libc::c_uint,
        N: libc::c_uchar,
    ) -> libc::c_int;
}
extern "C" {
    pub fn SDL_imageFilterMultByByte(
        Src1: *mut libc::c_uchar,
        Dest: *mut libc::c_uchar,
        length: libc::c_uint,
        C: libc::c_uchar,
    ) -> libc::c_int;
}
extern "C" {
    pub fn SDL_imageFilterShiftRightAndMultByByte(
        Src1: *mut libc::c_uchar,
        Dest: *mut libc::c_uchar,
        length: libc::c_uint,
        N: libc::c_uchar,
        C: libc::c_uchar,
    ) -> libc::c_int;
}
extern "C" {
    pub fn SDL_imageFilterShiftLeftByte(
        Src1: *mut libc::c_uchar,
        Dest: *mut libc::c_uchar,
        length: libc::c_uint,
        N: libc::c_uchar,
    ) -> libc::c_int;
}
extern "C" {
    pub fn SDL_imageFilterShiftLeftUint(
        Src1: *mut libc::c_uchar,
        Dest: *mut libc::c_uchar,
        length: libc::c_uint,
        N: libc::c_uchar,
    ) -> libc::c_int;
}
extern "C" {
    pub fn SDL_imageFilterShiftLeft(
        Src1: *mut libc::c_uchar,
        Dest: *mut libc::c_uchar,
        length: libc::c_uint,
        N: libc::c_uchar,
    ) -> libc::c_int;
}
extern "C" {
    pub fn SDL_imageFilterBinarizeUsingThreshold(
        Src1: *mut libc::c_uchar,
        Dest: *mut libc::c_uchar,
        length: libc::c_uint,
        T: libc::c_uchar,
    ) -> libc::c_int;
}
extern "C" {
    pub fn SDL_imageFilterClipToRange(
        Src1: *mut libc::c_uchar,
        Dest: *mut libc::c_uchar,
        length: libc::c_uint,
        Tmin: libc::c_uchar,
        Tmax: libc::c_uchar,
    ) -> libc::c_int;
}
extern "C" {
    pub fn SDL_imageFilterNormalizeLinear(
        Src: *mut libc::c_uchar,
        Dest: *mut libc::c_uchar,
        length: libc::c_uint,
        Cmin: libc::c_int,
        Cmax: libc::c_int,
        Nmin: libc::c_int,
        Nmax: libc::c_int,
    ) -> libc::c_int;
}
