/* automatically generated by rust-bindgen */

extern "C" {
    pub fn SDL_imageFilterMMXdetect() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn SDL_imageFilterMMXoff();
}
extern "C" {
    pub fn SDL_imageFilterMMXon();
}
extern "C" {
    pub fn SDL_imageFilterAdd(
        Src1: *mut ::std::os::raw::c_uchar,
        Src2: *mut ::std::os::raw::c_uchar,
        Dest: *mut ::std::os::raw::c_uchar,
        length: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn SDL_imageFilterMean(
        Src1: *mut ::std::os::raw::c_uchar,
        Src2: *mut ::std::os::raw::c_uchar,
        Dest: *mut ::std::os::raw::c_uchar,
        length: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn SDL_imageFilterSub(
        Src1: *mut ::std::os::raw::c_uchar,
        Src2: *mut ::std::os::raw::c_uchar,
        Dest: *mut ::std::os::raw::c_uchar,
        length: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn SDL_imageFilterAbsDiff(
        Src1: *mut ::std::os::raw::c_uchar,
        Src2: *mut ::std::os::raw::c_uchar,
        Dest: *mut ::std::os::raw::c_uchar,
        length: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn SDL_imageFilterMult(
        Src1: *mut ::std::os::raw::c_uchar,
        Src2: *mut ::std::os::raw::c_uchar,
        Dest: *mut ::std::os::raw::c_uchar,
        length: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn SDL_imageFilterMultNor(
        Src1: *mut ::std::os::raw::c_uchar,
        Src2: *mut ::std::os::raw::c_uchar,
        Dest: *mut ::std::os::raw::c_uchar,
        length: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn SDL_imageFilterMultDivby2(
        Src1: *mut ::std::os::raw::c_uchar,
        Src2: *mut ::std::os::raw::c_uchar,
        Dest: *mut ::std::os::raw::c_uchar,
        length: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn SDL_imageFilterMultDivby4(
        Src1: *mut ::std::os::raw::c_uchar,
        Src2: *mut ::std::os::raw::c_uchar,
        Dest: *mut ::std::os::raw::c_uchar,
        length: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn SDL_imageFilterBitAnd(
        Src1: *mut ::std::os::raw::c_uchar,
        Src2: *mut ::std::os::raw::c_uchar,
        Dest: *mut ::std::os::raw::c_uchar,
        length: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn SDL_imageFilterBitOr(
        Src1: *mut ::std::os::raw::c_uchar,
        Src2: *mut ::std::os::raw::c_uchar,
        Dest: *mut ::std::os::raw::c_uchar,
        length: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn SDL_imageFilterDiv(
        Src1: *mut ::std::os::raw::c_uchar,
        Src2: *mut ::std::os::raw::c_uchar,
        Dest: *mut ::std::os::raw::c_uchar,
        length: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn SDL_imageFilterBitNegation(
        Src1: *mut ::std::os::raw::c_uchar,
        Dest: *mut ::std::os::raw::c_uchar,
        length: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn SDL_imageFilterAddByte(
        Src1: *mut ::std::os::raw::c_uchar,
        Dest: *mut ::std::os::raw::c_uchar,
        length: ::std::os::raw::c_uint,
        C: ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn SDL_imageFilterAddUint(
        Src1: *mut ::std::os::raw::c_uchar,
        Dest: *mut ::std::os::raw::c_uchar,
        length: ::std::os::raw::c_uint,
        C: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn SDL_imageFilterAddByteToHalf(
        Src1: *mut ::std::os::raw::c_uchar,
        Dest: *mut ::std::os::raw::c_uchar,
        length: ::std::os::raw::c_uint,
        C: ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn SDL_imageFilterSubByte(
        Src1: *mut ::std::os::raw::c_uchar,
        Dest: *mut ::std::os::raw::c_uchar,
        length: ::std::os::raw::c_uint,
        C: ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn SDL_imageFilterSubUint(
        Src1: *mut ::std::os::raw::c_uchar,
        Dest: *mut ::std::os::raw::c_uchar,
        length: ::std::os::raw::c_uint,
        C: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn SDL_imageFilterShiftRight(
        Src1: *mut ::std::os::raw::c_uchar,
        Dest: *mut ::std::os::raw::c_uchar,
        length: ::std::os::raw::c_uint,
        N: ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn SDL_imageFilterShiftRightUint(
        Src1: *mut ::std::os::raw::c_uchar,
        Dest: *mut ::std::os::raw::c_uchar,
        length: ::std::os::raw::c_uint,
        N: ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn SDL_imageFilterMultByByte(
        Src1: *mut ::std::os::raw::c_uchar,
        Dest: *mut ::std::os::raw::c_uchar,
        length: ::std::os::raw::c_uint,
        C: ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn SDL_imageFilterShiftRightAndMultByByte(
        Src1: *mut ::std::os::raw::c_uchar,
        Dest: *mut ::std::os::raw::c_uchar,
        length: ::std::os::raw::c_uint,
        N: ::std::os::raw::c_uchar,
        C: ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn SDL_imageFilterShiftLeftByte(
        Src1: *mut ::std::os::raw::c_uchar,
        Dest: *mut ::std::os::raw::c_uchar,
        length: ::std::os::raw::c_uint,
        N: ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn SDL_imageFilterShiftLeftUint(
        Src1: *mut ::std::os::raw::c_uchar,
        Dest: *mut ::std::os::raw::c_uchar,
        length: ::std::os::raw::c_uint,
        N: ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn SDL_imageFilterShiftLeft(
        Src1: *mut ::std::os::raw::c_uchar,
        Dest: *mut ::std::os::raw::c_uchar,
        length: ::std::os::raw::c_uint,
        N: ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn SDL_imageFilterBinarizeUsingThreshold(
        Src1: *mut ::std::os::raw::c_uchar,
        Dest: *mut ::std::os::raw::c_uchar,
        length: ::std::os::raw::c_uint,
        T: ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn SDL_imageFilterClipToRange(
        Src1: *mut ::std::os::raw::c_uchar,
        Dest: *mut ::std::os::raw::c_uchar,
        length: ::std::os::raw::c_uint,
        Tmin: ::std::os::raw::c_uchar,
        Tmax: ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn SDL_imageFilterNormalizeLinear(
        Src: *mut ::std::os::raw::c_uchar,
        Dest: *mut ::std::os::raw::c_uchar,
        length: ::std::os::raw::c_uint,
        Cmin: ::std::os::raw::c_int,
        Cmax: ::std::os::raw::c_int,
        Nmin: ::std::os::raw::c_int,
        Nmax: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
