/* automatically generated by rust-bindgen 0.69.4 */

use crate::*;

pub const TTF_MAJOR_VERSION: u32 = 2;
pub const TTF_MINOR_VERSION: u32 = 22;
pub const TTF_PATCHLEVEL: u32 = 0;
pub const TTF_STYLE_NORMAL: u32 = 0;
pub const TTF_STYLE_BOLD: u32 = 1;
pub const TTF_STYLE_ITALIC: u32 = 2;
pub const TTF_STYLE_UNDERLINE: u32 = 4;
pub const TTF_STYLE_STRIKETHROUGH: u32 = 8;
pub const TTF_HINTING_NORMAL: u32 = 0;
pub const TTF_HINTING_LIGHT: u32 = 1;
pub const TTF_HINTING_MONO: u32 = 2;
pub const TTF_HINTING_NONE: u32 = 3;
pub const TTF_HINTING_LIGHT_SUBPIXEL: u32 = 4;
pub const TTF_WRAPPED_ALIGN_LEFT: u32 = 0;
pub const TTF_WRAPPED_ALIGN_CENTER: u32 = 1;
pub const TTF_WRAPPED_ALIGN_RIGHT: u32 = 2;
pub type __off_t = libc::c_long;
pub type __off64_t = libc::c_long;
pub type Uint8 = u8;
pub type Uint16 = u16;
pub type Uint32 = u32;
pub type Sint64 = i64;
extern "C" {
    pub fn TTF_Linked_Version() -> *const SDL_version;
}
extern "C" {
    pub fn TTF_GetFreeTypeVersion(
        major: *mut libc::c_int,
        minor: *mut libc::c_int,
        patch: *mut libc::c_int,
    );
}
extern "C" {
    pub fn TTF_GetHarfBuzzVersion(
        major: *mut libc::c_int,
        minor: *mut libc::c_int,
        patch: *mut libc::c_int,
    );
}
extern "C" {
    pub fn TTF_ByteSwappedUNICODE(swapped: SDL_bool);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _TTF_Font {
    _unused: [u8; 0],
}
pub type TTF_Font = _TTF_Font;
extern "C" {
    pub fn TTF_Init() -> libc::c_int;
}
extern "C" {
    pub fn TTF_OpenFont(file: *const libc::c_char, ptsize: libc::c_int) -> *mut TTF_Font;
}
extern "C" {
    pub fn TTF_OpenFontIndex(
        file: *const libc::c_char,
        ptsize: libc::c_int,
        index: libc::c_long,
    ) -> *mut TTF_Font;
}
extern "C" {
    pub fn TTF_OpenFontRW(
        src: *mut SDL_RWops,
        freesrc: libc::c_int,
        ptsize: libc::c_int,
    ) -> *mut TTF_Font;
}
extern "C" {
    pub fn TTF_OpenFontIndexRW(
        src: *mut SDL_RWops,
        freesrc: libc::c_int,
        ptsize: libc::c_int,
        index: libc::c_long,
    ) -> *mut TTF_Font;
}
extern "C" {
    pub fn TTF_OpenFontDPI(
        file: *const libc::c_char,
        ptsize: libc::c_int,
        hdpi: libc::c_uint,
        vdpi: libc::c_uint,
    ) -> *mut TTF_Font;
}
extern "C" {
    pub fn TTF_OpenFontIndexDPI(
        file: *const libc::c_char,
        ptsize: libc::c_int,
        index: libc::c_long,
        hdpi: libc::c_uint,
        vdpi: libc::c_uint,
    ) -> *mut TTF_Font;
}
extern "C" {
    pub fn TTF_OpenFontDPIRW(
        src: *mut SDL_RWops,
        freesrc: libc::c_int,
        ptsize: libc::c_int,
        hdpi: libc::c_uint,
        vdpi: libc::c_uint,
    ) -> *mut TTF_Font;
}
extern "C" {
    pub fn TTF_OpenFontIndexDPIRW(
        src: *mut SDL_RWops,
        freesrc: libc::c_int,
        ptsize: libc::c_int,
        index: libc::c_long,
        hdpi: libc::c_uint,
        vdpi: libc::c_uint,
    ) -> *mut TTF_Font;
}
extern "C" {
    pub fn TTF_SetFontSize(font: *mut TTF_Font, ptsize: libc::c_int) -> libc::c_int;
}
extern "C" {
    pub fn TTF_SetFontSizeDPI(
        font: *mut TTF_Font,
        ptsize: libc::c_int,
        hdpi: libc::c_uint,
        vdpi: libc::c_uint,
    ) -> libc::c_int;
}
extern "C" {
    pub fn TTF_GetFontStyle(font: *const TTF_Font) -> libc::c_int;
}
extern "C" {
    pub fn TTF_SetFontStyle(font: *mut TTF_Font, style: libc::c_int);
}
extern "C" {
    pub fn TTF_GetFontOutline(font: *const TTF_Font) -> libc::c_int;
}
extern "C" {
    pub fn TTF_SetFontOutline(font: *mut TTF_Font, outline: libc::c_int);
}
extern "C" {
    pub fn TTF_GetFontHinting(font: *const TTF_Font) -> libc::c_int;
}
extern "C" {
    pub fn TTF_SetFontHinting(font: *mut TTF_Font, hinting: libc::c_int);
}
extern "C" {
    pub fn TTF_GetFontWrappedAlign(font: *const TTF_Font) -> libc::c_int;
}
extern "C" {
    pub fn TTF_SetFontWrappedAlign(font: *mut TTF_Font, align: libc::c_int);
}
extern "C" {
    pub fn TTF_FontHeight(font: *const TTF_Font) -> libc::c_int;
}
extern "C" {
    pub fn TTF_FontAscent(font: *const TTF_Font) -> libc::c_int;
}
extern "C" {
    pub fn TTF_FontDescent(font: *const TTF_Font) -> libc::c_int;
}
extern "C" {
    pub fn TTF_FontLineSkip(font: *const TTF_Font) -> libc::c_int;
}
extern "C" {
    pub fn TTF_GetFontKerning(font: *const TTF_Font) -> libc::c_int;
}
extern "C" {
    pub fn TTF_SetFontKerning(font: *mut TTF_Font, allowed: libc::c_int);
}
extern "C" {
    pub fn TTF_FontFaces(font: *const TTF_Font) -> libc::c_long;
}
extern "C" {
    pub fn TTF_FontFaceIsFixedWidth(font: *const TTF_Font) -> libc::c_int;
}
extern "C" {
    pub fn TTF_FontFaceFamilyName(font: *const TTF_Font) -> *const libc::c_char;
}
extern "C" {
    pub fn TTF_FontFaceStyleName(font: *const TTF_Font) -> *const libc::c_char;
}
extern "C" {
    pub fn TTF_GlyphIsProvided(font: *mut TTF_Font, ch: Uint16) -> libc::c_int;
}
extern "C" {
    pub fn TTF_GlyphIsProvided32(font: *mut TTF_Font, ch: Uint32) -> libc::c_int;
}
extern "C" {
    pub fn TTF_GlyphMetrics(
        font: *mut TTF_Font,
        ch: Uint16,
        minx: *mut libc::c_int,
        maxx: *mut libc::c_int,
        miny: *mut libc::c_int,
        maxy: *mut libc::c_int,
        advance: *mut libc::c_int,
    ) -> libc::c_int;
}
extern "C" {
    pub fn TTF_GlyphMetrics32(
        font: *mut TTF_Font,
        ch: Uint32,
        minx: *mut libc::c_int,
        maxx: *mut libc::c_int,
        miny: *mut libc::c_int,
        maxy: *mut libc::c_int,
        advance: *mut libc::c_int,
    ) -> libc::c_int;
}
extern "C" {
    pub fn TTF_SizeText(
        font: *mut TTF_Font,
        text: *const libc::c_char,
        w: *mut libc::c_int,
        h: *mut libc::c_int,
    ) -> libc::c_int;
}
extern "C" {
    pub fn TTF_SizeUTF8(
        font: *mut TTF_Font,
        text: *const libc::c_char,
        w: *mut libc::c_int,
        h: *mut libc::c_int,
    ) -> libc::c_int;
}
extern "C" {
    pub fn TTF_SizeUNICODE(
        font: *mut TTF_Font,
        text: *const Uint16,
        w: *mut libc::c_int,
        h: *mut libc::c_int,
    ) -> libc::c_int;
}
extern "C" {
    pub fn TTF_MeasureText(
        font: *mut TTF_Font,
        text: *const libc::c_char,
        measure_width: libc::c_int,
        extent: *mut libc::c_int,
        count: *mut libc::c_int,
    ) -> libc::c_int;
}
extern "C" {
    pub fn TTF_MeasureUTF8(
        font: *mut TTF_Font,
        text: *const libc::c_char,
        measure_width: libc::c_int,
        extent: *mut libc::c_int,
        count: *mut libc::c_int,
    ) -> libc::c_int;
}
extern "C" {
    pub fn TTF_MeasureUNICODE(
        font: *mut TTF_Font,
        text: *const Uint16,
        measure_width: libc::c_int,
        extent: *mut libc::c_int,
        count: *mut libc::c_int,
    ) -> libc::c_int;
}
extern "C" {
    pub fn TTF_RenderText_Solid(
        font: *mut TTF_Font,
        text: *const libc::c_char,
        fg: SDL_Color,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn TTF_RenderUTF8_Solid(
        font: *mut TTF_Font,
        text: *const libc::c_char,
        fg: SDL_Color,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn TTF_RenderUNICODE_Solid(
        font: *mut TTF_Font,
        text: *const Uint16,
        fg: SDL_Color,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn TTF_RenderText_Solid_Wrapped(
        font: *mut TTF_Font,
        text: *const libc::c_char,
        fg: SDL_Color,
        wrapLength: Uint32,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn TTF_RenderUTF8_Solid_Wrapped(
        font: *mut TTF_Font,
        text: *const libc::c_char,
        fg: SDL_Color,
        wrapLength: Uint32,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn TTF_RenderUNICODE_Solid_Wrapped(
        font: *mut TTF_Font,
        text: *const Uint16,
        fg: SDL_Color,
        wrapLength: Uint32,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn TTF_RenderGlyph_Solid(
        font: *mut TTF_Font,
        ch: Uint16,
        fg: SDL_Color,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn TTF_RenderGlyph32_Solid(
        font: *mut TTF_Font,
        ch: Uint32,
        fg: SDL_Color,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn TTF_RenderText_Shaded(
        font: *mut TTF_Font,
        text: *const libc::c_char,
        fg: SDL_Color,
        bg: SDL_Color,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn TTF_RenderUTF8_Shaded(
        font: *mut TTF_Font,
        text: *const libc::c_char,
        fg: SDL_Color,
        bg: SDL_Color,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn TTF_RenderUNICODE_Shaded(
        font: *mut TTF_Font,
        text: *const Uint16,
        fg: SDL_Color,
        bg: SDL_Color,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn TTF_RenderText_Shaded_Wrapped(
        font: *mut TTF_Font,
        text: *const libc::c_char,
        fg: SDL_Color,
        bg: SDL_Color,
        wrapLength: Uint32,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn TTF_RenderUTF8_Shaded_Wrapped(
        font: *mut TTF_Font,
        text: *const libc::c_char,
        fg: SDL_Color,
        bg: SDL_Color,
        wrapLength: Uint32,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn TTF_RenderUNICODE_Shaded_Wrapped(
        font: *mut TTF_Font,
        text: *const Uint16,
        fg: SDL_Color,
        bg: SDL_Color,
        wrapLength: Uint32,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn TTF_RenderGlyph_Shaded(
        font: *mut TTF_Font,
        ch: Uint16,
        fg: SDL_Color,
        bg: SDL_Color,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn TTF_RenderGlyph32_Shaded(
        font: *mut TTF_Font,
        ch: Uint32,
        fg: SDL_Color,
        bg: SDL_Color,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn TTF_RenderText_Blended(
        font: *mut TTF_Font,
        text: *const libc::c_char,
        fg: SDL_Color,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn TTF_RenderUTF8_Blended(
        font: *mut TTF_Font,
        text: *const libc::c_char,
        fg: SDL_Color,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn TTF_RenderUNICODE_Blended(
        font: *mut TTF_Font,
        text: *const Uint16,
        fg: SDL_Color,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn TTF_RenderText_Blended_Wrapped(
        font: *mut TTF_Font,
        text: *const libc::c_char,
        fg: SDL_Color,
        wrapLength: Uint32,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn TTF_RenderUTF8_Blended_Wrapped(
        font: *mut TTF_Font,
        text: *const libc::c_char,
        fg: SDL_Color,
        wrapLength: Uint32,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn TTF_RenderUNICODE_Blended_Wrapped(
        font: *mut TTF_Font,
        text: *const Uint16,
        fg: SDL_Color,
        wrapLength: Uint32,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn TTF_RenderGlyph_Blended(
        font: *mut TTF_Font,
        ch: Uint16,
        fg: SDL_Color,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn TTF_RenderGlyph32_Blended(
        font: *mut TTF_Font,
        ch: Uint32,
        fg: SDL_Color,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn TTF_RenderText_LCD(
        font: *mut TTF_Font,
        text: *const libc::c_char,
        fg: SDL_Color,
        bg: SDL_Color,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn TTF_RenderUTF8_LCD(
        font: *mut TTF_Font,
        text: *const libc::c_char,
        fg: SDL_Color,
        bg: SDL_Color,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn TTF_RenderUNICODE_LCD(
        font: *mut TTF_Font,
        text: *const Uint16,
        fg: SDL_Color,
        bg: SDL_Color,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn TTF_RenderText_LCD_Wrapped(
        font: *mut TTF_Font,
        text: *const libc::c_char,
        fg: SDL_Color,
        bg: SDL_Color,
        wrapLength: Uint32,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn TTF_RenderUTF8_LCD_Wrapped(
        font: *mut TTF_Font,
        text: *const libc::c_char,
        fg: SDL_Color,
        bg: SDL_Color,
        wrapLength: Uint32,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn TTF_RenderUNICODE_LCD_Wrapped(
        font: *mut TTF_Font,
        text: *const Uint16,
        fg: SDL_Color,
        bg: SDL_Color,
        wrapLength: Uint32,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn TTF_RenderGlyph_LCD(
        font: *mut TTF_Font,
        ch: Uint16,
        fg: SDL_Color,
        bg: SDL_Color,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn TTF_RenderGlyph32_LCD(
        font: *mut TTF_Font,
        ch: Uint32,
        fg: SDL_Color,
        bg: SDL_Color,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn TTF_CloseFont(font: *mut TTF_Font);
}
extern "C" {
    pub fn TTF_Quit();
}
extern "C" {
    pub fn TTF_WasInit() -> libc::c_int;
}
extern "C" {
    pub fn TTF_GetFontKerningSize(
        font: *mut TTF_Font,
        prev_index: libc::c_int,
        index: libc::c_int,
    ) -> libc::c_int;
}
extern "C" {
    pub fn TTF_GetFontKerningSizeGlyphs(
        font: *mut TTF_Font,
        previous_ch: Uint16,
        ch: Uint16,
    ) -> libc::c_int;
}
extern "C" {
    pub fn TTF_GetFontKerningSizeGlyphs32(
        font: *mut TTF_Font,
        previous_ch: Uint32,
        ch: Uint32,
    ) -> libc::c_int;
}
extern "C" {
    pub fn TTF_SetFontSDF(font: *mut TTF_Font, on_off: SDL_bool) -> libc::c_int;
}
extern "C" {
    pub fn TTF_GetFontSDF(font: *const TTF_Font) -> SDL_bool;
}
pub const TTF_Direction_TTF_DIRECTION_LTR: TTF_Direction = 0;
pub const TTF_Direction_TTF_DIRECTION_RTL: TTF_Direction = 1;
pub const TTF_Direction_TTF_DIRECTION_TTB: TTF_Direction = 2;
pub const TTF_Direction_TTF_DIRECTION_BTT: TTF_Direction = 3;
pub type TTF_Direction = libc::c_uint;
extern "C" {
    pub fn TTF_SetDirection(direction: libc::c_int) -> libc::c_int;
}
extern "C" {
    pub fn TTF_SetScript(script: libc::c_int) -> libc::c_int;
}
extern "C" {
    pub fn TTF_SetFontDirection(font: *mut TTF_Font, direction: TTF_Direction) -> libc::c_int;
}
extern "C" {
    pub fn TTF_SetFontScriptName(font: *mut TTF_Font, script: *const libc::c_char) -> libc::c_int;
}
