//!
//! This crate was mainly generated by [`bindgen`](https://crates.io/crates/bindgen). It should be enough in most cases,
//! but if you ever find discrepancies between what bindgen generated and your OS, you can always
//! [generate your own `sdl2-sys`](https://github.com/rust-sdl2/rust-sdl2#generating-sdl2-sys-with-bindgen).
//!

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
// suppress warnings about u128 (that we don't even use ourselves anyway)
#![allow(improper_ctypes)]
#![no_std]

include!(concat!(env!("OUT_DIR"), "/sdl_bindings.rs"));

#[cfg(feature = "mixer")]
pub mod mixer;

#[cfg(feature = "image")]
pub mod image;

#[cfg(feature = "ttf")]
pub mod ttf;

#[cfg(feature = "gfx")]
pub mod gfx;
