use std::ffi::{CString, CStr};
use libc::c_char;

use sys::keycode as ll;

#[derive(Copy, Clone, Eq, PartialEq, Hash, Debug)]
#[repr(i32)]
pub enum Keycode {
    Backspace          = ll::SDLK_BACKSPACE as i32,
    Tab                = ll::SDLK_TAB as i32,
    Return             = ll::SDLK_RETURN as i32,
    Escape             = ll::SDLK_ESCAPE as i32,
    Space              = ll::SDLK_SPACE as i32,
    Exclaim            = ll::SDLK_EXCLAIM as i32,
    Quotedbl           = ll::SDLK_QUOTEDBL as i32,
    Hash               = ll::SDLK_HASH as i32,
    Dollar             = ll::SDLK_DOLLAR as i32,
    Percent            = ll::SDLK_PERCENT as i32,
    Ampersand          = ll::SDLK_AMPERSAND as i32,
    Quote              = ll::SDLK_QUOTE as i32,
    LeftParen          = ll::SDLK_LEFTPAREN as i32,
    RightParen         = ll::SDLK_RIGHTPAREN as i32,
    Asterisk           = ll::SDLK_ASTERISK as i32,
    Plus               = ll::SDLK_PLUS as i32,
    Comma              = ll::SDLK_COMMA as i32,
    Minus              = ll::SDLK_MINUS as i32,
    Period             = ll::SDLK_PERIOD as i32,
    Slash              = ll::SDLK_SLASH as i32,
    Num0               = ll::SDLK_0 as i32,
    Num1               = ll::SDLK_1 as i32,
    Num2               = ll::SDLK_2 as i32,
    Num3               = ll::SDLK_3 as i32,
    Num4               = ll::SDLK_4 as i32,
    Num5               = ll::SDLK_5 as i32,
    Num6               = ll::SDLK_6 as i32,
    Num7               = ll::SDLK_7 as i32,
    Num8               = ll::SDLK_8 as i32,
    Num9               = ll::SDLK_9 as i32,
    Colon              = ll::SDLK_COLON as i32,
    Semicolon          = ll::SDLK_SEMICOLON as i32,
    Less               = ll::SDLK_LESS as i32,
    Equals             = ll::SDLK_EQUALS as i32,
    Greater            = ll::SDLK_GREATER as i32,
    Question           = ll::SDLK_QUESTION as i32,
    At                 = ll::SDLK_AT as i32,
    LeftBracket        = ll::SDLK_LEFTBRACKET as i32,
    Backslash          = ll::SDLK_BACKSLASH as i32,
    RightBracket       = ll::SDLK_RIGHTBRACKET as i32,
    Caret              = ll::SDLK_CARET as i32,
    Underscore         = ll::SDLK_UNDERSCORE as i32,
    Backquote          = ll::SDLK_BACKQUOTE as i32,
    A                  = ll::SDLK_a as i32,
    B                  = ll::SDLK_b as i32,
    C                  = ll::SDLK_c as i32,
    D                  = ll::SDLK_d as i32,
    E                  = ll::SDLK_e as i32,
    F                  = ll::SDLK_f as i32,
    G                  = ll::SDLK_g as i32,
    H                  = ll::SDLK_h as i32,
    I                  = ll::SDLK_i as i32,
    J                  = ll::SDLK_j as i32,
    K                  = ll::SDLK_k as i32,
    L                  = ll::SDLK_l as i32,
    M                  = ll::SDLK_m as i32,
    N                  = ll::SDLK_n as i32,
    O                  = ll::SDLK_o as i32,
    P                  = ll::SDLK_p as i32,
    Q                  = ll::SDLK_q as i32,
    R                  = ll::SDLK_r as i32,
    S                  = ll::SDLK_s as i32,
    T                  = ll::SDLK_t as i32,
    U                  = ll::SDLK_u as i32,
    V                  = ll::SDLK_v as i32,
    W                  = ll::SDLK_w as i32,
    X                  = ll::SDLK_x as i32,
    Y                  = ll::SDLK_y as i32,
    Z                  = ll::SDLK_z as i32,
    Delete             = ll::SDLK_DELETE as i32,
    CapsLock           = ll::SDLK_CAPSLOCK as i32,
    F1                 = ll::SDLK_F1 as i32,
    F2                 = ll::SDLK_F2 as i32,
    F3                 = ll::SDLK_F3 as i32,
    F4                 = ll::SDLK_F4 as i32,
    F5                 = ll::SDLK_F5 as i32,
    F6                 = ll::SDLK_F6 as i32,
    F7                 = ll::SDLK_F7 as i32,
    F8                 = ll::SDLK_F8 as i32,
    F9                 = ll::SDLK_F9 as i32,
    F10                = ll::SDLK_F10 as i32,
    F11                = ll::SDLK_F11 as i32,
    F12                = ll::SDLK_F12 as i32,
    PrintScreen        = ll::SDLK_PRINTSCREEN as i32,
    ScrollLock         = ll::SDLK_SCROLLLOCK as i32,
    Pause              = ll::SDLK_PAUSE as i32,
    Insert             = ll::SDLK_INSERT as i32,
    Home               = ll::SDLK_HOME as i32,
    PageUp             = ll::SDLK_PAGEUP as i32,
    End                = ll::SDLK_END as i32,
    PageDown           = ll::SDLK_PAGEDOWN as i32,
    Right              = ll::SDLK_RIGHT as i32,
    Left               = ll::SDLK_LEFT as i32,
    Down               = ll::SDLK_DOWN as i32,
    Up                 = ll::SDLK_UP as i32,
    NumLockClear       = ll::SDLK_NUMLOCKCLEAR as i32,
    KpDivide           = ll::SDLK_KPDIVIDE as i32,
    KpMultiply         = ll::SDLK_KPMULTIPLY as i32,
    KpMinus            = ll::SDLK_KPMINUS as i32,
    KpPlus             = ll::SDLK_KPPLUS as i32,
    KpEnter            = ll::SDLK_KPENTER as i32,
    Kp1                = ll::SDLK_KP1 as i32,
    Kp2                = ll::SDLK_KP2 as i32,
    Kp3                = ll::SDLK_KP3 as i32,
    Kp4                = ll::SDLK_KP4 as i32,
    Kp5                = ll::SDLK_KP5 as i32,
    Kp6                = ll::SDLK_KP6 as i32,
    Kp7                = ll::SDLK_KP7 as i32,
    Kp8                = ll::SDLK_KP8 as i32,
    Kp9                = ll::SDLK_KP9 as i32,
    Kp0                = ll::SDLK_KP0 as i32,
    KpPeriod           = ll::SDLK_KPPERIOD as i32,
    Application        = ll::SDLK_APPLICATION as i32,
    Power              = ll::SDLK_POWER as i32,
    KpEquals           = ll::SDLK_KPEQUALS as i32,
    F13                = ll::SDLK_F13 as i32,
    F14                = ll::SDLK_F14 as i32,
    F15                = ll::SDLK_F15 as i32,
    F16                = ll::SDLK_F16 as i32,
    F17                = ll::SDLK_F17 as i32,
    F18                = ll::SDLK_F18 as i32,
    F19                = ll::SDLK_F19 as i32,
    F20                = ll::SDLK_F20 as i32,
    F21                = ll::SDLK_F21 as i32,
    F22                = ll::SDLK_F22 as i32,
    F23                = ll::SDLK_F23 as i32,
    F24                = ll::SDLK_F24 as i32,
    Execute            = ll::SDLK_EXECUTE as i32,
    Help               = ll::SDLK_HELP as i32,
    Menu               = ll::SDLK_MENU as i32,
    Select             = ll::SDLK_SELECT as i32,
    Stop               = ll::SDLK_STOP as i32,
    Again              = ll::SDLK_AGAIN as i32,
    Undo               = ll::SDLK_UNDO as i32,
    Cut                = ll::SDLK_CUT as i32,
    Copy               = ll::SDLK_COPY as i32,
    Paste              = ll::SDLK_PASTE as i32,
    Find               = ll::SDLK_FIND as i32,
    Mute               = ll::SDLK_MUTE as i32,
    VolumeUp           = ll::SDLK_VOLUMEUP as i32,
    VolumeDown         = ll::SDLK_VOLUMEDOWN as i32,
    KpComma            = ll::SDLK_KPCOMMA as i32,
    KpEqualsAS400      = ll::SDLK_KPEQUALSAS400 as i32,
    AltErase           = ll::SDLK_ALTERASE as i32,
    Sysreq             = ll::SDLK_SYSREQ as i32,
    Cancel             = ll::SDLK_CANCEL as i32,
    Clear              = ll::SDLK_CLEAR as i32,
    Prior              = ll::SDLK_PRIOR as i32,
    Return2            = ll::SDLK_RETURN2 as i32,
    Separator          = ll::SDLK_SEPARATOR as i32,
    Out                = ll::SDLK_OUT as i32,
    Oper               = ll::SDLK_OPER as i32,
    ClearAgain         = ll::SDLK_CLEARAGAIN as i32,
    CrSel              = ll::SDLK_CRSEL as i32,
    ExSel              = ll::SDLK_EXSEL as i32,
    Kp00               = ll::SDLK_KP00 as i32,
    Kp000              = ll::SDLK_KP000 as i32,
    ThousandsSeparator = ll::SDLK_THOUSANDSSEPARATOR as i32,
    DecimalSeparator   = ll::SDLK_DECIMALSEPARATOR as i32,
    CurrencyUnit       = ll::SDLK_CURRENCYUNIT as i32,
    CurrencySubUnit    = ll::SDLK_CURRENCYSUBUNIT as i32,
    KpLeftParen        = ll::SDLK_KPLEFTPAREN as i32,
    KpRightParen       = ll::SDLK_KPRIGHTPAREN as i32,
    KpLeftBrace        = ll::SDLK_KPLEFTBRACE as i32,
    KpRightBrace       = ll::SDLK_KPRIGHTBRACE as i32,
    KpTab              = ll::SDLK_KPTAB as i32,
    KpBackspace        = ll::SDLK_KPBACKSPACE as i32,
    KpA                = ll::SDLK_KPA as i32,
    KpB                = ll::SDLK_KPB as i32,
    KpC                = ll::SDLK_KPC as i32,
    KpD                = ll::SDLK_KPD as i32,
    KpE                = ll::SDLK_KPE as i32,
    KpF                = ll::SDLK_KPF as i32,
    KpXor              = ll::SDLK_KPXOR as i32,
    KpPower            = ll::SDLK_KPPOWER as i32,
    KpPercent          = ll::SDLK_KPPERCENT as i32,
    KpLess             = ll::SDLK_KPLESS as i32,
    KpGreater          = ll::SDLK_KPGREATER as i32,
    KpAmpersand        = ll::SDLK_KPAMPERSAND as i32,
    KpDblAmpersand     = ll::SDLK_KPDBLAMPERSAND as i32,
    KpVerticalBar      = ll::SDLK_KPVERTICALBAR as i32,
    KpDblVerticalBar   = ll::SDLK_KPDBLVERTICALBAR as i32,
    KpColon            = ll::SDLK_KPCOLON as i32,
    KpHash             = ll::SDLK_KPHASH as i32,
    KpSpace            = ll::SDLK_KPSPACE as i32,
    KpAt               = ll::SDLK_KPAT as i32,
    KpExclam           = ll::SDLK_KPEXCLAM as i32,
    KpMemStore         = ll::SDLK_KPMEMSTORE as i32,
    KpMemRecall        = ll::SDLK_KPMEMRECALL as i32,
    KpMemClear         = ll::SDLK_KPMEMCLEAR as i32,
    KpMemAdd           = ll::SDLK_KPMEMADD as i32,
    KpMemSubtract      = ll::SDLK_KPMEMSUBTRACT as i32,
    KpMemMultiply      = ll::SDLK_KPMEMMULTIPLY as i32,
    KpMemDivide        = ll::SDLK_KPMEMDIVIDE as i32,
    KpPlusMinus        = ll::SDLK_KPPLUSMINUS as i32,
    KpClear            = ll::SDLK_KPCLEAR as i32,
    KpClearEntry       = ll::SDLK_KPCLEARENTRY as i32,
    KpBinary           = ll::SDLK_KPBINARY as i32,
    KpOctal            = ll::SDLK_KPOCTAL as i32,
    KpDecimal          = ll::SDLK_KPDECIMAL as i32,
    KpHexadecimal      = ll::SDLK_KPHEXADECIMAL as i32,
    LCtrl              = ll::SDLK_LCTRL as i32,
    LShift             = ll::SDLK_LSHIFT as i32,
    LAlt               = ll::SDLK_LALT as i32,
    LGui               = ll::SDLK_LGUI as i32,
    RCtrl              = ll::SDLK_RCTRL as i32,
    RShift             = ll::SDLK_RSHIFT as i32,
    RAlt               = ll::SDLK_RALT as i32,
    RGui               = ll::SDLK_RGUI as i32,
    Mode               = ll::SDLK_MODE as i32,
    AudioNext          = ll::SDLK_AUDIONEXT as i32,
    AudioPrev          = ll::SDLK_AUDIOPREV as i32,
    AudioStop          = ll::SDLK_AUDIOSTOP as i32,
    AudioPlay          = ll::SDLK_AUDIOPLAY as i32,
    AudioMute          = ll::SDLK_AUDIOMUTE as i32,
    MediaSelect        = ll::SDLK_MEDIASELECT as i32,
    Www                = ll::SDLK_WWW as i32,
    Mail               = ll::SDLK_MAIL as i32,
    Calculator         = ll::SDLK_CALCULATOR as i32,
    Computer           = ll::SDLK_COMPUTER as i32,
    AcSearch           = ll::SDLK_ACSEARCH as i32,
    AcHome             = ll::SDLK_ACHOME as i32,
    AcBack             = ll::SDLK_ACBACK as i32,
    AcForward          = ll::SDLK_ACFORWARD as i32,
    AcStop             = ll::SDLK_ACSTOP as i32,
    AcRefresh          = ll::SDLK_ACREFRESH as i32,
    AcBookmarks        = ll::SDLK_ACBOOKMARKS as i32,
    BrightnessDown     = ll::SDLK_BRIGHTNESSDOWN as i32,
    BrightnessUp       = ll::SDLK_BRIGHTNESSUP as i32,
    DisplaySwitch      = ll::SDLK_DISPLAYSWITCH as i32,
    KbdIllumToggle     = ll::SDLK_KBDILLUMTOGGLE as i32,
    KbdIllumDown       = ll::SDLK_KBDILLUMDOWN as i32,
    KbdIllumUp         = ll::SDLK_KBDILLUMUP as i32,
    Eject              = ll::SDLK_EJECT as i32,
    Sleep              = ll::SDLK_SLEEP as i32,
}

impl Keycode {
    pub fn from_i32(n: i32) -> Option<Keycode> {
        use self::Keycode::*;

        Some( match n as ll::SDL_Keycode {
            ll::SDLK_UNKNOWN             => return None,
            ll::SDLK_BACKSPACE           => Backspace,
            ll::SDLK_TAB                 => Tab,
            ll::SDLK_RETURN              => Return,
            ll::SDLK_ESCAPE              => Escape,
            ll::SDLK_SPACE               => Space,
            ll::SDLK_EXCLAIM             => Exclaim,
            ll::SDLK_QUOTEDBL            => Quotedbl,
            ll::SDLK_HASH                => Hash,
            ll::SDLK_DOLLAR              => Dollar,
            ll::SDLK_PERCENT             => Percent,
            ll::SDLK_AMPERSAND           => Ampersand,
            ll::SDLK_QUOTE               => Quote,
            ll::SDLK_LEFTPAREN           => LeftParen,
            ll::SDLK_RIGHTPAREN          => RightParen,
            ll::SDLK_ASTERISK            => Asterisk,
            ll::SDLK_PLUS                => Plus,
            ll::SDLK_COMMA               => Comma,
            ll::SDLK_MINUS               => Minus,
            ll::SDLK_PERIOD              => Period,
            ll::SDLK_SLASH               => Slash,
            ll::SDLK_0                   => Num0,
            ll::SDLK_1                   => Num1,
            ll::SDLK_2                   => Num2,
            ll::SDLK_3                   => Num3,
            ll::SDLK_4                   => Num4,
            ll::SDLK_5                   => Num5,
            ll::SDLK_6                   => Num6,
            ll::SDLK_7                   => Num7,
            ll::SDLK_8                   => Num8,
            ll::SDLK_9                   => Num9,
            ll::SDLK_COLON               => Colon,
            ll::SDLK_SEMICOLON           => Semicolon,
            ll::SDLK_LESS                => Less,
            ll::SDLK_EQUALS              => Equals,
            ll::SDLK_GREATER             => Greater,
            ll::SDLK_QUESTION            => Question,
            ll::SDLK_AT                  => At,
            ll::SDLK_LEFTBRACKET         => LeftBracket,
            ll::SDLK_BACKSLASH           => Backslash,
            ll::SDLK_RIGHTBRACKET        => RightBracket,
            ll::SDLK_CARET               => Caret,
            ll::SDLK_UNDERSCORE          => Underscore,
            ll::SDLK_BACKQUOTE           => Backquote,
            ll::SDLK_a                   => A,
            ll::SDLK_b                   => B,
            ll::SDLK_c                   => C,
            ll::SDLK_d                   => D,
            ll::SDLK_e                   => E,
            ll::SDLK_f                   => F,
            ll::SDLK_g                   => G,
            ll::SDLK_h                   => H,
            ll::SDLK_i                   => I,
            ll::SDLK_j                   => J,
            ll::SDLK_k                   => K,
            ll::SDLK_l                   => L,
            ll::SDLK_m                   => M,
            ll::SDLK_n                   => N,
            ll::SDLK_o                   => O,
            ll::SDLK_p                   => P,
            ll::SDLK_q                   => Q,
            ll::SDLK_r                   => R,
            ll::SDLK_s                   => S,
            ll::SDLK_t                   => T,
            ll::SDLK_u                   => U,
            ll::SDLK_v                   => V,
            ll::SDLK_w                   => W,
            ll::SDLK_x                   => X,
            ll::SDLK_y                   => Y,
            ll::SDLK_z                   => Z,
            ll::SDLK_DELETE              => Delete,
            ll::SDLK_CAPSLOCK            => CapsLock,
            ll::SDLK_F1                  => F1,
            ll::SDLK_F2                  => F2,
            ll::SDLK_F3                  => F3,
            ll::SDLK_F4                  => F4,
            ll::SDLK_F5                  => F5,
            ll::SDLK_F6                  => F6,
            ll::SDLK_F7                  => F7,
            ll::SDLK_F8                  => F8,
            ll::SDLK_F9                  => F9,
            ll::SDLK_F10                 => F10,
            ll::SDLK_F11                 => F11,
            ll::SDLK_F12                 => F12,
            ll::SDLK_PRINTSCREEN         => PrintScreen,
            ll::SDLK_SCROLLLOCK          => ScrollLock,
            ll::SDLK_PAUSE               => Pause,
            ll::SDLK_INSERT              => Insert,
            ll::SDLK_HOME                => Home,
            ll::SDLK_PAGEUP              => PageUp,
            ll::SDLK_END                 => End,
            ll::SDLK_PAGEDOWN            => PageDown,
            ll::SDLK_RIGHT               => Right,
            ll::SDLK_LEFT                => Left,
            ll::SDLK_DOWN                => Down,
            ll::SDLK_UP                  => Up,
            ll::SDLK_NUMLOCKCLEAR        => NumLockClear,
            ll::SDLK_KPDIVIDE            => KpDivide,
            ll::SDLK_KPMULTIPLY          => KpMultiply,
            ll::SDLK_KPMINUS             => KpMinus,
            ll::SDLK_KPPLUS              => KpPlus,
            ll::SDLK_KPENTER             => KpEnter,
            ll::SDLK_KP1                 => Kp1,
            ll::SDLK_KP2                 => Kp2,
            ll::SDLK_KP3                 => Kp3,
            ll::SDLK_KP4                 => Kp4,
            ll::SDLK_KP5                 => Kp5,
            ll::SDLK_KP6                 => Kp6,
            ll::SDLK_KP7                 => Kp7,
            ll::SDLK_KP8                 => Kp8,
            ll::SDLK_KP9                 => Kp9,
            ll::SDLK_KP0                 => Kp0,
            ll::SDLK_KPPERIOD            => KpPeriod,
            ll::SDLK_APPLICATION         => Application,
            ll::SDLK_POWER               => Power,
            ll::SDLK_KPEQUALS            => KpEquals,
            ll::SDLK_F13                 => F13,
            ll::SDLK_F14                 => F14,
            ll::SDLK_F15                 => F15,
            ll::SDLK_F16                 => F16,
            ll::SDLK_F17                 => F17,
            ll::SDLK_F18                 => F18,
            ll::SDLK_F19                 => F19,
            ll::SDLK_F20                 => F20,
            ll::SDLK_F21                 => F21,
            ll::SDLK_F22                 => F22,
            ll::SDLK_F23                 => F23,
            ll::SDLK_F24                 => F24,
            ll::SDLK_EXECUTE             => Execute,
            ll::SDLK_HELP                => Help,
            ll::SDLK_MENU                => Menu,
            ll::SDLK_SELECT              => Select,
            ll::SDLK_STOP                => Stop,
            ll::SDLK_AGAIN               => Again,
            ll::SDLK_UNDO                => Undo,
            ll::SDLK_CUT                 => Cut,
            ll::SDLK_COPY                => Copy,
            ll::SDLK_PASTE               => Paste,
            ll::SDLK_FIND                => Find,
            ll::SDLK_MUTE                => Mute,
            ll::SDLK_VOLUMEUP            => VolumeUp,
            ll::SDLK_VOLUMEDOWN          => VolumeDown,
            ll::SDLK_KPCOMMA             => KpComma,
            ll::SDLK_KPEQUALSAS400       => KpEqualsAS400,
            ll::SDLK_ALTERASE            => AltErase,
            ll::SDLK_SYSREQ              => Sysreq,
            ll::SDLK_CANCEL              => Cancel,
            ll::SDLK_CLEAR               => Clear,
            ll::SDLK_PRIOR               => Prior,
            ll::SDLK_RETURN2             => Return2,
            ll::SDLK_SEPARATOR           => Separator,
            ll::SDLK_OUT                 => Out,
            ll::SDLK_OPER                => Oper,
            ll::SDLK_CLEARAGAIN          => ClearAgain,
            ll::SDLK_CRSEL               => CrSel,
            ll::SDLK_EXSEL               => ExSel,
            ll::SDLK_KP00                => Kp00,
            ll::SDLK_KP000               => Kp000,
            ll::SDLK_THOUSANDSSEPARATOR  => ThousandsSeparator,
            ll::SDLK_DECIMALSEPARATOR    => DecimalSeparator,
            ll::SDLK_CURRENCYUNIT        => CurrencyUnit,
            ll::SDLK_CURRENCYSUBUNIT     => CurrencySubUnit,
            ll::SDLK_KPLEFTPAREN         => KpLeftParen,
            ll::SDLK_KPRIGHTPAREN        => KpRightParen,
            ll::SDLK_KPLEFTBRACE         => KpLeftBrace,
            ll::SDLK_KPRIGHTBRACE        => KpRightBrace,
            ll::SDLK_KPTAB               => KpTab,
            ll::SDLK_KPBACKSPACE         => KpBackspace,
            ll::SDLK_KPA                 => KpA,
            ll::SDLK_KPB                 => KpB,
            ll::SDLK_KPC                 => KpC,
            ll::SDLK_KPD                 => KpD,
            ll::SDLK_KPE                 => KpE,
            ll::SDLK_KPF                 => KpF,
            ll::SDLK_KPXOR               => KpXor,
            ll::SDLK_KPPOWER             => KpPower,
            ll::SDLK_KPPERCENT           => KpPercent,
            ll::SDLK_KPLESS              => KpLess,
            ll::SDLK_KPGREATER           => KpGreater,
            ll::SDLK_KPAMPERSAND         => KpAmpersand,
            ll::SDLK_KPDBLAMPERSAND      => KpDblAmpersand,
            ll::SDLK_KPVERTICALBAR       => KpVerticalBar,
            ll::SDLK_KPDBLVERTICALBAR    => KpDblVerticalBar,
            ll::SDLK_KPCOLON             => KpColon,
            ll::SDLK_KPHASH              => KpHash,
            ll::SDLK_KPSPACE             => KpSpace,
            ll::SDLK_KPAT                => KpAt,
            ll::SDLK_KPEXCLAM            => KpExclam,
            ll::SDLK_KPMEMSTORE          => KpMemStore,
            ll::SDLK_KPMEMRECALL         => KpMemRecall,
            ll::SDLK_KPMEMCLEAR          => KpMemClear,
            ll::SDLK_KPMEMADD            => KpMemAdd,
            ll::SDLK_KPMEMSUBTRACT       => KpMemSubtract,
            ll::SDLK_KPMEMMULTIPLY       => KpMemMultiply,
            ll::SDLK_KPMEMDIVIDE         => KpMemDivide,
            ll::SDLK_KPPLUSMINUS         => KpPlusMinus,
            ll::SDLK_KPCLEAR             => KpClear,
            ll::SDLK_KPCLEARENTRY        => KpClearEntry,
            ll::SDLK_KPBINARY            => KpBinary,
            ll::SDLK_KPOCTAL             => KpOctal,
            ll::SDLK_KPDECIMAL           => KpDecimal,
            ll::SDLK_KPHEXADECIMAL       => KpHexadecimal,
            ll::SDLK_LCTRL               => LCtrl,
            ll::SDLK_LSHIFT              => LShift,
            ll::SDLK_LALT                => LAlt,
            ll::SDLK_LGUI                => LGui,
            ll::SDLK_RCTRL               => RCtrl,
            ll::SDLK_RSHIFT              => RShift,
            ll::SDLK_RALT                => RAlt,
            ll::SDLK_RGUI                => RGui,
            ll::SDLK_MODE                => Mode,
            ll::SDLK_AUDIONEXT           => AudioNext,
            ll::SDLK_AUDIOPREV           => AudioPrev,
            ll::SDLK_AUDIOSTOP           => AudioStop,
            ll::SDLK_AUDIOPLAY           => AudioPlay,
            ll::SDLK_AUDIOMUTE           => AudioMute,
            ll::SDLK_MEDIASELECT         => MediaSelect,
            ll::SDLK_WWW                 => Www,
            ll::SDLK_MAIL                => Mail,
            ll::SDLK_CALCULATOR          => Calculator,
            ll::SDLK_COMPUTER            => Computer,
            ll::SDLK_ACSEARCH            => AcSearch,
            ll::SDLK_ACHOME              => AcHome,
            ll::SDLK_ACBACK              => AcBack,
            ll::SDLK_ACFORWARD           => AcForward,
            ll::SDLK_ACSTOP              => AcStop,
            ll::SDLK_ACREFRESH           => AcRefresh,
            ll::SDLK_ACBOOKMARKS         => AcBookmarks,
            ll::SDLK_BRIGHTNESSDOWN      => BrightnessDown,
            ll::SDLK_BRIGHTNESSUP        => BrightnessUp,
            ll::SDLK_DISPLAYSWITCH       => DisplaySwitch,
            ll::SDLK_KBDILLUMTOGGLE      => KbdIllumToggle,
            ll::SDLK_KBDILLUMDOWN        => KbdIllumDown,
            ll::SDLK_KBDILLUMUP          => KbdIllumUp,
            ll::SDLK_EJECT               => Eject,
            ll::SDLK_SLEEP               => Sleep,
            _                            => return None,
        })
    }
}

use std::fmt;

impl fmt::Display for Keycode {
    fn fmt(&self, f: &mut fmt::Formatter) -> Result<(), fmt::Error> {
        write!(f, "{}", self.name())
    }
}

use keyboard::Scancode;

impl Keycode {
    /// Gets the virtual key from a scancode. Returns None if there is no corresponding virtual key.
    pub fn from_scancode(scancode: Scancode) -> Option<Keycode> {
        unsafe {
            match ::sys::keyboard::SDL_GetKeyFromScancode(scancode as u32) {
                ll::SDLK_UNKNOWN => None,
                keycode_id => Keycode::from_i32(keycode_id as i32)
            }
        }
    }

    pub fn from_name(name: &str) -> Option<Keycode> {
        unsafe {
            match CString::new(name) {
                Ok(name) => match ::sys::keyboard::SDL_GetKeyFromName(name.as_ptr() as *const c_char) {
                    ll::SDLK_UNKNOWN => None,
                    keycode_id => Some(Keycode::from_i32(keycode_id as i32).unwrap())
                },
                // string contains a nul byte - it won't match anything.
                Err(_) => None
            }
        }
    }

    pub fn name(self) -> String {
        // The name string pointer's contents _might_ change, depending on the last call to SDL_GetKeyName.
        // Knowing this, we must always return a new string.
        unsafe {
            let buf = ::sys::keyboard::SDL_GetKeyName(self as i32);
            CStr::from_ptr(buf as *const _).to_str().unwrap().to_owned()
        }
    }
}
